services:
  cricverse:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cricverse
    ports:
      - "3000:3000"
    restart: unless-stopped
    environment:
      NODE_ENV: production
